config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders, only: %i[create index show]
  resources :games
  resources :genres
  resources :cart do
    post "increment"
    post "decrement"
  end

  resources :checkout, only: %i[index update create success]

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  root to: "home#index"
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :authenticate_user!

  def index
    @subtotal = 0
    @pst_rate = Province.find(current_user.province_id).PST
    @gst_rate = Province.find(current_user.province_id).GST
    @user_province = Province.find(current_user.province_id).code
    @user = current_user

    cart.each do |game|
      @subtotal += game[0].price * game[1]
    end

    @pst = @subtotal * @pst_rate
    @gst = @subtotal * @gst_rate
    @total = @subtotal + @gst + @pst
  end

  def update
    @user = User.find_by(id: current_user.id)
    @user.update(user_params)
    redirect_to checkout_index_path
  end

  def create
    cart_items = []
    @subtotal = 0
    @pst_rate = Province.find(current_user.province_id).PST
    @gst_rate = Province.find(current_user.province_id).GST
    @user_province = Province.find(current_user.province_id).code
    @user = current_user

    cart.each do |game|
      @subtotal += game[0].price * game[1]
    end

    @pst = @subtotal * @pst_rate
    @gst = @subtotal * @gst_rate

    session[:cart].each do |game|
      cart_items << { name:     Game.find(game[0]).title,
                      amount:   (Game.find(game[0]).price * 100).to_i,
                      currency: "cad",
                      quantity: game[1] }
    end

    unless Province.find(current_user.province_id).PST.nil?
      cart_items << { name:     "PST/HST",
                      amount:   (@pst * 100).to_i,
                      currency: "cad",
                      quantity: 1 }
    end

    if @gst.positive?
      cart_items << { name:     "GST",
                      amount:   (@gst * 100).to_i,
                      currency: "cad",
                      quantity: 1 }
    end

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      success_url:          "#{checkout_success_url}?session_id={CHECKOUT_SESSION_ID}",
      cancel_url:           checkout_cancel_url,
      line_items:           cart_items
    )

    respond_to do |format|
      format.js
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
    # An error occurred with the payment
  end

  def checkout_params
    params.permit(:order_id, :pst, :gst)
  end

  def user_params
    params.permit(:province_id, :address, :postal, :city)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/cancel.html.erb
<h1 class="display-3">Oops!  Something went wrong with the payment. 😢</h1>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function(result) {
  console.log(result.error.message);
})

app/views/checkout/index.html.erb
<h1 class="display-2">Checkout</h1>

<% if cart.present? %>
  <% if !@user.province_id.present? || !@user.address.present? || !@user.postal_code.present? || !@user.city.present?%>
    <%= form_with url: checkout_path(@user.id, :id, :address, :postal, :city), method: :put do |f| %>
      <h1 class="display-6 my-3">Your Details</h1>
      <div class="field">
        <%= f.label :address, class: "form-label" %><br />
        <%= f.text_field :address, class: "form-control min-vw-25 w-50", value: @user.address %>
      </div>

      <div class="field">
        <%= f.label :city %><br />
        <%= f.text_field :city, autocomplete: "city", class: "form-control min-vw-25 w-50", value: @user.city %>
      </div>

      <div class="field">
        <%= f.label :postal_code %><br />
        <%= f.text_field :postal_code, autocomplete: "postal-code", class: "form-control min-vw-25 w-50", value: @user.postal_code %>
      </div>

      <div class="field">
        <%= f.label :province %><br />
        <%= f.collection_select :province_id, Province.all, :id, :code, { :prompt => 'Select a Province', :selected => @user.province_id }, { class: 'form-control min-vw-10 w-25' } %>
      </div>

      <%= button_tag 'Update' %>
    <% end %>
  <% end %>
    <h1 class="display-6 my-3">Order Summary</h1>

    <div class="table-responsive">
      <table class="table table-hover">
        <tr>
          <td>Game</td>
          <td class="text-end">Price</td>
          <td class="text-end">Quantity</td>
          <td></td>
        </tr>
        <% cart.each do |game| %>
          <tr>
            <td><%= game[0].title %></td>
            <td class="text-end"><%= game[0].price %></td>
            <td class="text-end d-flex justify-content-end">
              <!-- Show decrement button if qty is greater than 1 -->
              <% if game[1] > 1 %>
                <%= form_with url: cart_decrement_path(game), method: :decrement do %>
                    <%= hidden_field_tag(:cart_id, game[0].id) %>
                    <%= button_tag '-', class: "btn-sm btn-secondary mx-1 my-1"  %>
                <% end %>
              <% end %>
              <div class="m-1">
                <%= game[1] %>
              </div>
              <%= form_with url: cart_increment_path(game), method: :increment do %>
                  <%= hidden_field_tag(:cart_id, game[0].id) %>
                  <%= button_tag '+', class: "btn-sm btn-secondary mx-1 my-1" %>
              <% end %>
            </td>
            <td class="text-end">
              <%= form_with url: cart_path(game), method: :delete do %>
                <%= hidden_field_tag(:game_id, game[0].id) %>
                <%= button_tag 'Delete from Cart', class: "btn-sm" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        <tfoot>
          <tr>
            <td class="text-end">Subtotal</td>
            <td class="text-end"><%= sprintf("%.2f", @subtotal) %> </td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td class="text-end">Taxes</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td class="text-end">PST/HST</td>
            <td class="text-end"><%= sprintf("%.2f", @pst) %></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td class="text-end">GST</td>
            <td class="text-end"><%= sprintf("%.2f", @gst) %></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td class="text-end">Total</td>
            <td class="text-end"><%= sprintf("%.2f", @total) %> </td>
            <td></td>
            <td></td>
          </tr>
        </tfoot>
      </table>

      <%= button_to 'Submit Order', { controller: 'checkout', action: 'create', pst: :pst, gst: :gst }, { method: :post, remote: true } %>
    </div>
<% else %>
  <h1 class="display-6">There are no items in your cart.</h1>
<% end %>

app/views/checkout/success.html.erb
<h1 class="display-3 text-center m-5">Stripe payment completed!</h1>

<div class="w-100 d-flex justify-content-center">
  <%= button_to "Complete your order", { controller: "orders",
                                       action: "create",
                                       stripe_payment_id: @payment_intent.id,
                                       paid: @payment_intent.charges.data[0].paid,
                                       paid_amount: @payment_intent.charges.data[0].amount_captured / 100.00 }, class: "btn btn-primary m-5" %>
</div>