config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders, only: %i[create index show]
  resources :games
  resources :genres
  resources :cart do
    post "increment"
    post "decrement"
  end

  resources :checkout, only: %i[index update create success]

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  root to: "home#index"
end

app/models/game.rb
class Game < ApplicationRecord
  paginates_per 25

  # has_many :game_genres, dependent: :delete_all
  # has_many :genres, through: :game_genres
  belongs_to :genre

  has_many :game_orders, dependent: :delete_all
  has_many :orders, through: :game_orders

  belongs_to :developer

  validates :title, uniqueness: true, presence: true
  validates :metascore, numericality: { only_integer: true }
  validates :price, numericality: true

  def self.search(search, genre = nil)
    if search && genre.nil?
      game = where("LOWER(games.title) LIKE ?", "#{search.downcase}%")

      if game
        game = where("LOWER(games.title) LIKE ?", "#{search.downcase}%")
      else
        Game.all
      end
    elsif search && !genre.nil?
      game = where("LOWER(games.title) LIKE ?",
                   "#{search.downcase}%").where(genre_id: genre[:id].to_i)

      if game
        game = where("LOWER(games.title) LIKE ?",
                     "#{search.downcase}%").where(genre_id: genre[:id].to_i)
      else
        Game.all
      end
    elsif !search && !genre.nil?
      genre_filter(genre)
    else
      Game.all
    end
  end

  def self.genre_filter(genre)
    if genre
      game = where(genre_id: genre[:id].to_i)

      if game
        game = where(genre_id: genre[:id].to_i)
      else
        Game.all
      end
    else
      Game.all
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games or /games.json
  def index
    @games = Game.search(params[:search], params[:genre]).page(params[:page])
    @genres_searched ||= []

    @games.each_with_index do |g, index|
      @genres_searched[index] = g.genre_id
    end

    @genres = Genre.all
  end

  # GET /games/1 or /games/1.json
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_foreign_keys
    @game_order = GameOrder.where(game_id: :id).delete_all
    @game_genre = GameGenre.where(game_id: :id).delete_all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:title, :developer_id, :genre_id, :metascore, :price)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<h1 class="my-3 display-4">
  <%= @game.title%>
</h1>

<div>
  <div>
    <p>Developer : <%= @game.developer.name %></p>
  </div>
  <div>
    <p>Metascore: <%= @game.metascore %> </p>
  </div>
  <div>
    <p>Price: <%= @game.price %></p>
  </div>
  <div>
    <p>Genre:</p>
    <div>
      <%= @game.genre.title %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<h1 class="display-2 text-center">Games</h1>

<%= form_tag(games_path, method: :get) do %>
  <%= collection_select :genre, :id, Genre.where(id: @genres_searched).order('title ASC'), :id, :title, {prompt: 'Filter by genre...'}, { class: 'form-control mb-3 w-25', onchange: 'this.form.submit();' } %>
  <%= hidden_field_tag(:search, params[:search])%>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Developer</th>
      <th>Metascore</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.developer.name %></td>
        <td><%= game.metascore %></td>
        <td><%= game.price %></td>
        <td><%= link_to 'Show', game %></td>
        <td>
          <% if cart.include?(game) %>
            <%= link_to 'Remove from Cart', cart_path(game), method: :delete %>
          <% else %>
            <% form_with url: cart_index_path, method: :post %>
              <%= hidden_field_tag(:game_id, game.id) %>
              <%= link_to 'Add to Cart' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= paginate @games %>
</div>

app/views/games/show.html.erb
<%= render partial: 'game', object: @game, locals: { show_link: false } %>