config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders, only: %i[create index show]
  resources :games
  resources :genres
  resources :cart do
    post "increment"
    post "decrement"
  end

  resources :checkout, only: %i[index update create success]

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EGaming</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <a class="navbar-brand mx-2">eGaming</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Home", root_path, class: "nav-item nav-link text-decoration-none" %>
          <%= link_to "Games", games_path, class: "nav-item nav-link text-decoration-none" %>
          <%= link_to "Genres", genres_path, class: "nav-item nav-link text-decoration-none" %>
        </div>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <ul class="navbar-nav ms-auto">
              <li>
                <%= link_to "Admin Console", "/admin", class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
              <li class="nav-item">
                <%= link_to "Order History", orders_path, class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
              <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
              <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
              <li>
                <%= link_to "Login", new_user_session_path, class: "nav-item nav-link ms-auto btn-sm btn-secondary m-1 text-white text-decoration-none" %>
              </li>
            </ul>
          <% end %>
          <%= link_to "Cart <span class='badge bg-info'>#{cart.count}</span>".html_safe, checkout_index_path, class: "btn btn-secondary nav-item nav-link text-decoration-none text-white" %>
          <%= form_tag(games_path, method: :get, class: "d-flex mx-2") do %>
            <%= text_field_tag(:search, params[:search], class: "form-control me-2", placeholder: "Search games...") %>
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          <% end %>
        </ul>
      </div>
    </nav>
    <section class="m-4">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </section>
  </body>
</html>